// <auto-generated />
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FinalProject.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20200203022350_AddThreeTable")]
    partial class AddThreeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.Blog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Description");

                    b.Property<string>("MedicineName");

                    b.Property<string>("Name");

                    b.Property<DateTime>("PostTime");

                    b.Property<string>("State");

                    b.Property<string>("StreetNumberAndName");

                    b.Property<int>("UserID");

                    b.Property<string>("ZipCode");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("FinalProject.Models.Pharmacy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("DEANumber");

                    b.Property<string>("Email");

                    b.Property<string>("NPINumber");

                    b.Property<string>("Password");

                    b.Property<string>("PharmacyName");

                    b.Property<string>("State");

                    b.Property<string>("StreetNumberAndName");

                    b.Property<string>("ZipCode");

                    b.HasKey("ID");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("FinalProject.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinalProject.Models.Blog", b =>
                {
                    b.HasOne("FinalProject.Models.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
